In [1]:
import numpy as np

In [2]:
t=np.genfromtxt(r"C:\Users\pavan\Downloads\tipsf.csv",delimiter=",",skip_header=1)

In [3]:
t

array([[  0.  ,  16.99,   1.01, ...,   1.  ,   0.  ,   2.  ],
       [  1.  ,  10.34,   1.66, ...,   1.  ,   0.  ,   3.  ],
       [  2.  ,  21.01,   3.5 , ...,   1.  ,   0.  ,   3.  ],
       ...,
       [241.  ,  22.67,   2.  , ...,   0.  ,   0.  ,   2.  ],
       [242.  ,  17.82,   1.75, ...,   0.  ,   0.  ,   2.  ],
       [243.  ,  18.78,   3.  , ...,   2.  ,   0.  ,   2.  ]])

# 1. what is the total bill value?

In [12]:
np.sum(t[:,1])

4827.77

# 2. what is the total tip value?

In [13]:
np.sum(t[:,2])

731.5799999999999

# 3. count how many times sunday,saturday,thursday,friday are there.

# 4. how many smokers are there?

In [15]:
x=np.sum(t[:,4])
print(x)

93.0


# 5. what is the average tip given by female and male?

In [20]:
x1=np.sum(t[:,2].take(np.where(t[:,3]==0)))
x2=np.sum(t[:,2].take(np.where(t[:,3]==1)))
y1=np.unique(t[:,3],return_counts=True)
s,u=y1
print(x1/u[0],"average tip by female")
print(x1/u[1],"average tip by male")

2.8334482758620685 average tip by female
1.5701273885350315 average tip by male


# 6. how much amount have been spent by female and male.

In [21]:
x1=np.sum(t[:,1].take(np.where(t[:,3]==0)))
x2=np.sum(t[:,1].take(np.where(t[:,3]==1)))
print(x1,"=amount spent by females")
print(x2,"=amount spent by females")

1570.9499999999996 =amount spent by females
3256.8199999999997 =amount spent by females


# 7. what is the min and max tip given?

In [23]:
mintip=np.min(t[:,2])
maxtip=np.max(t[:,2])
print("minimum tip given ",mintip)
print("maximum tip given ",maxtip)

minimum tip given  1.0
maximum tip given  10.0


# 8. how many male and female are going for dinner and lunch?

# 9. find out the average size?

In [26]:
np.mean(t[:,7])

2.569672131147541

# 10. how many female and male smokers are there?

# second question train_extended

In [4]:
x=np.genfromtxt(r"C:\Users\pavan\Downloads\train_extended.csv",delimiter=",",skip_header=1)

In [5]:
x

array([[ 1.575     ,  1.225     ,  0.375     , ...,  6.3219385 ,
         9.63883   , 10.        ],
       [ 1.2375    ,  1.        ,  0.375     , ...,  3.798833  ,
         7.654365  , 19.        ],
       [ 1.45      ,  1.1625    ,  0.4125    , ...,  7.01650125,
         7.257472  , 11.        ],
       ...,
       [ 1.125     ,  0.9125    ,  0.2875    , ...,  1.984465  ,
         3.118445  ,  7.        ],
       [ 1.625     ,  1.275     ,  0.4125    , ...,  7.86698625,
        10.489315  , 11.        ],
       [ 1.5875    ,  1.25      ,  0.3875    , ...,  7.38504475,
         8.788345  , 11.        ]])

# 1. what is max and min length?

In [29]:
np.max(x[:,0])

7.58349125

In [30]:
np.min(x[:,0])

0.0

# 2. difference between max and min length?

In [32]:
y=np.max(x[:,0])-np.min(x[:,0])
print("difference of max and min is ",y)

difference of max and min is  7.58349125


# 3. find column wise average?

In [33]:
np.mean(x,axis=0)

array([ 1.31244808,  1.02032036,  0.34602787, 23.12343631,  9.98937025,
        4.99318096,  6.63422915,  9.950615  ])

# 4. find out all the age whose height is greater than 0.4?

In [42]:
t=x[:,2].take(np.where(x[:,2]>0.4))
print(t)

[[0.4125 0.4375 0.4375 ... 0.425  0.4375 0.4125]]


# 5. what is the average height and weight of the persons who age is 10?

In [8]:
y1=np.array(x[:,2].take(np.where(x[:,7]==10)))
print("average height whose age is 10 ",np.mean(y1))
y2=np.array(x[:,3].take(np.where(x[:,7]==10)))
print("average weight whose age is 10 ",np.mean(y2))

average height whose age is 10  0.3833672856539947
average weight whose age is 10  28.243308450511314


# 6. what is total shell weight?

In [9]:
np.sum(x[:,6])

1326845.8295214002

# 7. how many people belongs to each and every unique age?

In [11]:
a=np.unique(x[:,7],return_counts=True)
print(a)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 29.]), array([   46,    42,   625,  2787,  5475, 12450, 18276, 26818, 32906,
       30803, 23457, 12717, 10037,  6352,  4831,  3191,  2705,  1953,
        1591,  1206,   721,   296,   352,   110,    51,    46,    99,
          57], dtype=int64))


# 8. difference between shuckled and viscera weight?

In [12]:
x1=np.sum(x[:,4])
x2=np.sum(x[:,5])
print(x1-x2)

999237.8582600503


# 9. avg height of person whose age is greater than 14 and less than 19?

In [16]:
y1=np.array(x[:,2].take(np.where((x[:,7]>14) & (x[:,7]<19))))
print(np.mean(y1))

0.4190701892744479


# 10. avg weight if we include all weights?

In [17]:
s1=np.sum(x[:3:7])
count=list(x.shape)

In [22]:
print(np.round(s1),count[0])

73.0 200000
